apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-server-application
  namespace: argocd
spec:
  project: api
  source:
    repoURL: https://github.com/doccilabs/gitops-platform.git
    path: gitops-server
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: api
  syncPolicy:
    automated:
      selfHeal: true
      enabled: false
